document.documentElement.classList.add('js');
const STORE_LINKS={edge:{label:'免费添加到 Edge',url:'https://microsoftedge.microsoft.com/addons/detail/%E9%B2%B8%E9%B1%BCai%E5%8A%A9%E6%89%8B/lgfpicokhhemdpohohdlffponcillpfa'},chrome:{label:'免费添加到 Chrome',url:'https://chromewebstore.google.com/detail/%E9%B2%B8%E9%B1%BCai%E5%8A%A9%E6%89%8B-deepseek%E5%AF%BC%E5%87%BAword/foegcdhddlencjjkaeonjahfcdlmlihl'},firefox:{label:'免费添加到 Firefox',url:'https://addons.mozilla.org/zh-CN/firefox/addon/deepseek%E5%AF%BC%E5%87%BAword-%E9%B2%B8%E9%B1%BCai%E5%8A%A9%E6%89%8B/'},qihu:{label:'免费添加到 360 浏览器',url:'https://ext.se.360.cn/#/extension-detail?id=hgahdgilffiglaefnmnkoclmigdaighg'}};
function browserStore(){const ua=navigator.userAgent;if(/Firefox\//i.test(ua))return STORE_LINKS.firefox;if(/Edg\//i.test(ua))return STORE_LINKS.edge;if(/360SE|360EE|QIHU/i.test(ua))return STORE_LINKS.qihu;if(/Chrome\//i.test(ua))return STORE_LINKS.chrome;return STORE_LINKS.edge}
function track(name,details={}){const payload={event:name,...details};window.dataLayer=window.dataLayer||[];window.dataLayer.push(payload);window.dispatchEvent(new CustomEvent('deepseek-exporter:analytics',{detail:payload}))}
const preferredStore=browserStore();document.querySelectorAll('[data-store-cta]').forEach(link=>{link.href=preferredStore.url;const label=link.querySelector('[data-store-label]');if(label)label.textContent=preferredStore.label;link.addEventListener('click',()=>track('store_cta_click',{location:link.dataset.ctaLocation||'unknown',destination:preferredStore.label}))});document.querySelectorAll('[data-outbound]').forEach(link=>link.addEventListener('click',()=>track('store_cta_click',{location:'browser_grid',destination:link.dataset.outbound})));
const header=document.querySelector('[data-header]'),menuButton=document.querySelector('[data-menu-toggle]'),mobileMenu=document.querySelector('[data-mobile-menu]');function closeMenu(){if(!menuButton||!mobileMenu)return;menuButton.setAttribute('aria-expanded','false');mobileMenu.classList.remove('open');document.body.classList.remove('menu-open')}if(menuButton&&mobileMenu){menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));mobileMenu.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});mobileMenu.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu()})}
const stickyCta=document.querySelector('.mobile-sticky-cta');function onScroll(){if(header)header.classList.toggle('scrolled',scrollY>8);if(stickyCta)stickyCta.classList.toggle('visible',scrollY>560)}addEventListener('scroll',onScroll,{passive:true});onScroll();
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{rootMargin:'0px 0px -8% 0px',threshold:.08});reveals.forEach(item=>observer.observe(item))}else reveals.forEach(item=>item.classList.add('visible'));
const featureData=[{image:'/images/banner-2.png',alt:'DeepSeek Exporter 导出偏好设置',label:'完整保留内容结构'},{image:'/images/banner-3.png',alt:'DeepSeek 深度思考过程导出',label:'思考过程与答案清晰分层'},{image:'/images/banner-4.png',alt:'DeepSeek 对话批量导出',label:'一次整理多个高价值对话'},{image:'/images/banner-5.png',alt:'DeepSeek 回答高亮标注',label:'阅读、标注、收藏形成闭环'}],featureImage=document.querySelector('[data-feature-image]'),featureLabel=document.querySelector('[data-feature-label]');document.querySelectorAll('[data-feature-tab]').forEach(tab=>tab.addEventListener('click',()=>{const index=Number(tab.dataset.featureTab);document.querySelectorAll('[data-feature-tab]').forEach(item=>{item.classList.toggle('active',item===tab);item.setAttribute('aria-selected',String(item===tab))});if(featureImage){featureImage.src=featureData[index].image;featureImage.alt=featureData[index].alt}if(featureLabel)featureLabel.textContent=featureData[index].label;track('feature_preview',{feature:index+1})}));
document.querySelectorAll('.faq-list details').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)track('faq_expand',{question:item.querySelector('summary')?.innerText.replace('＋','').trim()})}));
